# -*- coding: utf-8 -*-
"""calculator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1N0XdQKh-BhsbdlgHWCmpC7Ae_ijYZDva
"""

# Online Python compiler (interpreter) to run Python online.
import statistics

def get_numbers(prompt="Enter numbers separated by spaces: "):
    while True:
        try:
            nums = list(map(float, input(prompt).split()))
            if nums:
                return nums
            print("Please enter at least one number.")
        except ValueError:0
            print("Invalid input. Please enter valid numbers.")

def get_two_numbers():
    while True:
        try:
            a = float(input("Enter first number: "))
            b = float(input("Enter second number: "))
            return a, b
        except ValueError:
            print("Invalid input. Please enter valid numbers.")

def calculator():
    print("=" * 45)
    print("        PYTHON CALCULATOR")
    print("=" * 45)
    print("Operations:")
    print("  1. Addition          (+)")
    print("  2. Subtraction       (-)")
    print("  3. Multiplication    (*)")
    print("  4. Division          (/)")
    print("  5. Percentage        (%)")
    print("  6. Mean")
    print("  7. Median")
    print("  8. Mode")
    print("  9. Average (same as Mean)")
    print("  0. Exit")
    print("=" * 45)

    while True:
        choice = input("\nChoose an operation (0-9): ").strip()

        if choice == "0":
            print("Goodbye!")
            break

        elif choice == "1":
            a, b = get_two_numbers()
            result = a + b
            print(f"\nResult: {a} + {b} = {result}")

        elif choice == "2":
            a, b = get_two_numbers()
            result = a - b
            print(f"\nResult: {a} - {b} = {result}")

        elif choice == "3":
            a, b = get_two_numbers()
            result = a * b
            print(f"\nResult: {a} * {b} = {result}")

        elif choice == "4":
            a, b = get_two_numbers()
            if b == 0:
                print("\nError: Division by zero is not allowed.")
            else:
                result = a / b
                print(f"\nResult: {a} / {b} = {result}")

        elif choice == "5":
            while True:
                try:
                    value = float(input("Enter the value: "))
                    percent = float(input("Enter the percentage: "))
                    break
                except ValueError:
                    print("Invalid input.")
            result = (percent / 100) * value
            print(f"\nResult: {percent}% of {value} = {result}")

        elif choice in ("6", "9"):
            nums = get_numbers()
            result = statistics.mean(nums)
            label = "Mean/Average"
            print(f"\n{label} of {nums} = {result}")

        elif choice == "7":
            nums = get_numbers()
            result = statistics.median(nums)
            print(f"\nMedian of {nums} = {result}")

        elif choice == "8":
            nums = get_numbers()
            try:
                result = statistics.mode(nums)
                print(f"\nMode of {nums} = {result}")
            except statistics.StatisticsError:
                print("\nNo unique mode found (multiple values appear equally often).")

        else:
            print("Invalid choice. Please select 0-9.")

if __name__ == "__main__":
    calculator()